IRIT_DIR = ./irit-sm
include $(IRIT_DIR)/makeflag.unx

CC         = g++
CFLAGS = -Wc++11-compat -Wextra -Wall -std=c++11 -O2
OBJECTS = common.o iritSkel.o obj.o voxelizer.o
HEADERS = $(wildcard *.h)

voxelizer: $(OBJECTS) $(HEADERS) makefile.unx main.o
	$(CC) $(CFLAGS) -o voxelizer  $(IRIT_LIBS) $(OBJECTS) main.o -DDEBUG

clean:
	rm -f *.o *.a voxelizer

%.o: %.cpp $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@
