IRIT_DIR = ./irit-sm

include $(IRIT_DIR)/makeflag.unx

CC         = g++
CFLAGS = -Wc++11-compat -Wextra -std=c++11 -O2
OBJECTS = common.o iritSkel.o obj.o voxelizer.o
HEADERS = $(wildcard *.h)

voxelizer: $(OBJECTS) $(HEADERS) makefile.unx main.o
	$(CC) $(CFLAGS) $(IRIT_LIBS) -lm -o vox $(OBJECTS) main.o

clean:
	rm -f *.o vox *.a

%.o: %.cpp $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@
